steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/app:v1', '.']
  timeout: 180s
  id: 'build-docker-image'
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/app:v1']
  id: 'push-docker-image'
  waitFor: ['build-docker-image']
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=k8/
  - --location=us-west1-b
  - --cluster=project-kube
  id: 'deploy-container'
  waitFor: ['push-docker-image']
