apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator-deployment
  labels:
    app: Text_Translator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Text_Translator
  template:
    metadata:
      labels:
        app: Text_Translator
    spec:
      containers:
      - name: translator-app
        image: gcr.io/$PROJECT_ID/app:v1
        ports:
        - containerPort: 8080
